// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: acc_user_info_query.sql

package database

import (
	"context"
	"database/sql"
)

const addUserAutoUserId = `-- name: AddUserAutoUserId :execresult



INSERT INTO ` + "`" + `acc_user_info` + "`" + ` (
    user_account, user_nickname, user_avatar, user_state, user_phone, 
    user_gender, user_birthday, user_is_authentication
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type AddUserAutoUserIdParams struct {
	UserAccount          string
	UserNickname         sql.NullString
	UserAvatar           sql.NullString
	UserState            uint8
	UserPhone            sql.NullString
	UserGender           sql.NullInt16
	UserBirthday         sql.NullTime
	UserIsAuthentication uint8
}

// -- name: UpdatePassword :exec
// UPDATE `acc_user_info` SET user_password = ? WHERE user_id = ?;
func (q *Queries) AddUserAutoUserId(ctx context.Context, arg AddUserAutoUserIdParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addUserAutoUserId,
		arg.UserAccount,
		arg.UserNickname,
		arg.UserAvatar,
		arg.UserState,
		arg.UserPhone,
		arg.UserGender,
		arg.UserBirthday,
		arg.UserIsAuthentication,
	)
}

const addUserHaveUserId = `-- name: AddUserHaveUserId :execresult
INSERT INTO ` + "`" + `acc_user_info` + "`" + ` (
    user_id, user_account, user_nickname, user_avatar, user_state, user_phone, 
    user_gender, user_birthday,  user_is_authentication
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type AddUserHaveUserIdParams struct {
	UserID               uint64
	UserAccount          string
	UserNickname         sql.NullString
	UserAvatar           sql.NullString
	UserState            uint8
	UserPhone            sql.NullString
	UserGender           sql.NullInt16
	UserBirthday         sql.NullTime
	UserIsAuthentication uint8
}

func (q *Queries) AddUserHaveUserId(ctx context.Context, arg AddUserHaveUserIdParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addUserHaveUserId,
		arg.UserID,
		arg.UserAccount,
		arg.UserNickname,
		arg.UserAvatar,
		arg.UserState,
		arg.UserPhone,
		arg.UserGender,
		arg.UserBirthday,
		arg.UserIsAuthentication,
	)
}

const deleteForceUser = `-- name: DeleteForceUser :exec
DELETE FROM acc_user_info WHERE user_account = ?
`

func (q *Queries) DeleteForceUser(ctx context.Context, userAccount string) error {
	_, err := q.db.ExecContext(ctx, deleteForceUser, userAccount)
	return err
}

const editUserByUserId = `-- name: EditUserByUserId :execresult
UPDATE ` + "`" + `acc_user_info` + "`" + `
SET user_nickname = ?, user_avatar = ?, user_phone = ?, 
user_gender = ?, user_birthday = ?, user_updated_at = NOW()
WHERE user_id = ? AND user_is_authentication = 1
`

type EditUserByUserIdParams struct {
	UserNickname sql.NullString
	UserAvatar   sql.NullString
	UserPhone    sql.NullString
	UserGender   sql.NullInt16
	UserBirthday sql.NullTime
	UserID       uint64
}

func (q *Queries) EditUserByUserId(ctx context.Context, arg EditUserByUserIdParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, editUserByUserId,
		arg.UserNickname,
		arg.UserAvatar,
		arg.UserPhone,
		arg.UserGender,
		arg.UserBirthday,
		arg.UserID,
	)
}

const findUsers = `-- name: FindUsers :many
SELECT user_id, user_account, user_nickname, user_avatar, user_state, user_phone, user_gender, user_birthday, user_address, user_is_authentication, user_created_at, user_updated_at, user_deleted_at FROM acc_user_info WHERE user_account LIKE ? OR user_nickname LIKE ?
`

type FindUsersParams struct {
	UserAccount  string
	UserNickname sql.NullString
}

func (q *Queries) FindUsers(ctx context.Context, arg FindUsersParams) ([]AccUserInfo, error) {
	rows, err := q.db.QueryContext(ctx, findUsers, arg.UserAccount, arg.UserNickname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccUserInfo
	for rows.Next() {
		var i AccUserInfo
		if err := rows.Scan(
			&i.UserID,
			&i.UserAccount,
			&i.UserNickname,
			&i.UserAvatar,
			&i.UserState,
			&i.UserPhone,
			&i.UserGender,
			&i.UserBirthday,
			&i.UserAddress,
			&i.UserIsAuthentication,
			&i.UserCreatedAt,
			&i.UserUpdatedAt,
			&i.UserDeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByUserId = `-- name: GetUserByUserId :one
SELECT 
    user_id,
    user_account,
    user_nickname,
    user_avatar,
    user_state,
    user_phone,
    user_gender,
    user_birthday,
    user_is_authentication,
    user_created_at,
    user_updated_at
FROM ` + "`" + `acc_user_info` + "`" + `
WHERE user_id = ? LIMIT 1
`

type GetUserByUserIdRow struct {
	UserID               uint64
	UserAccount          string
	UserNickname         sql.NullString
	UserAvatar           sql.NullString
	UserState            uint8
	UserPhone            sql.NullString
	UserGender           sql.NullInt16
	UserBirthday         sql.NullTime
	UserIsAuthentication uint8
	UserCreatedAt        sql.NullTime
	UserUpdatedAt        sql.NullTime
}

func (q *Queries) GetUserByUserId(ctx context.Context, userID uint64) (GetUserByUserIdRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUserId, userID)
	var i GetUserByUserIdRow
	err := row.Scan(
		&i.UserID,
		&i.UserAccount,
		&i.UserNickname,
		&i.UserAvatar,
		&i.UserState,
		&i.UserPhone,
		&i.UserGender,
		&i.UserBirthday,
		&i.UserIsAuthentication,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT user_id,
    user_account,
    user_nickname,
    user_avatar,
    user_state,
    user_phone,
    user_gender,
    user_birthday,
    user_is_authentication,
    user_created_at,
    user_updated_at 
FROM acc_user_info 
WHERE user_id IN (?)
`

type GetUsersRow struct {
	UserID               uint64
	UserAccount          string
	UserNickname         sql.NullString
	UserAvatar           sql.NullString
	UserState            uint8
	UserPhone            sql.NullString
	UserGender           sql.NullInt16
	UserBirthday         sql.NullTime
	UserIsAuthentication uint8
	UserCreatedAt        sql.NullTime
	UserUpdatedAt        sql.NullTime
}

func (q *Queries) GetUsers(ctx context.Context, userID uint64) ([]GetUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getUsers, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersRow
	for rows.Next() {
		var i GetUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.UserAccount,
			&i.UserNickname,
			&i.UserAvatar,
			&i.UserState,
			&i.UserPhone,
			&i.UserGender,
			&i.UserBirthday,
			&i.UserIsAuthentication,
			&i.UserCreatedAt,
			&i.UserUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT user_id, user_account, user_nickname, user_avatar, user_state, user_phone, user_gender, user_birthday, user_address, user_is_authentication, user_created_at, user_updated_at, user_deleted_at FROM acc_user_info LIMIT ? OFFSET ?
`

type ListUsersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]AccUserInfo, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccUserInfo
	for rows.Next() {
		var i AccUserInfo
		if err := rows.Scan(
			&i.UserID,
			&i.UserAccount,
			&i.UserNickname,
			&i.UserAvatar,
			&i.UserState,
			&i.UserPhone,
			&i.UserGender,
			&i.UserBirthday,
			&i.UserAddress,
			&i.UserIsAuthentication,
			&i.UserCreatedAt,
			&i.UserUpdatedAt,
			&i.UserDeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUser = `-- name: RemoveUser :exec
DELETE FROM acc_user_info WHERE user_id = ?
`

func (q *Queries) RemoveUser(ctx context.Context, userID uint64) error {
	_, err := q.db.ExecContext(ctx, removeUser, userID)
	return err
}
