// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type AccUserTwoFactorTwoFactorAuthType string

const (
	AccUserTwoFactorTwoFactorAuthTypeSMS   AccUserTwoFactorTwoFactorAuthType = "SMS"
	AccUserTwoFactorTwoFactorAuthTypeEMAIL AccUserTwoFactorTwoFactorAuthType = "EMAIL"
	AccUserTwoFactorTwoFactorAuthTypeAPP   AccUserTwoFactorTwoFactorAuthType = "APP"
)

func (e *AccUserTwoFactorTwoFactorAuthType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccUserTwoFactorTwoFactorAuthType(s)
	case string:
		*e = AccUserTwoFactorTwoFactorAuthType(s)
	default:
		return fmt.Errorf("unsupported scan type for AccUserTwoFactorTwoFactorAuthType: %T", src)
	}
	return nil
}

type NullAccUserTwoFactorTwoFactorAuthType struct {
	AccUserTwoFactorTwoFactorAuthType AccUserTwoFactorTwoFactorAuthType
	Valid                             bool // Valid is true if AccUserTwoFactorTwoFactorAuthType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccUserTwoFactorTwoFactorAuthType) Scan(value interface{}) error {
	if value == nil {
		ns.AccUserTwoFactorTwoFactorAuthType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccUserTwoFactorTwoFactorAuthType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccUserTwoFactorTwoFactorAuthType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccUserTwoFactorTwoFactorAuthType), nil
}

// account_user_base
type AccUserBase struct {
	UserID         int32
	UserAccount    string
	UserPassword   string
	UserSalt       string
	UserLoginTime  sql.NullTime
	UserLogoutTime sql.NullTime
	UserLoginIp    sql.NullString
	UserCreatedAt  sql.NullTime
	UserUpdatedAt  sql.NullTime
	UserDeletedAt  sql.NullTime
	// authentication is enabled for the user
	IsTwoFactorEnabled sql.NullInt32
}

// acc_user_info
type AccUserInfo struct {
	// User ID
	UserID uint64
	// User account
	UserAccount string
	// User nickname
	UserNickname sql.NullString
	// User avatar
	UserAvatar sql.NullString
	// User state: 0-Locked, 1-Activated, 2-Not Activated
	UserState uint8
	// Mobile phone number
	UserPhone sql.NullString
	// User gender: 0-Secret, 1-Male, 2-Female
	UserGender sql.NullInt16
	// User birthday
	UserBirthday sql.NullTime
	// User address
	UserAddress sql.NullString
	// Authentication status: 0-Not Authenticated, 1-Pending, 2-Authenticated, 3-Failed
	UserIsAuthentication uint8
	// Record creation time
	CreatedAt sql.NullTime
	// Record update time
	UpdatedAt sql.NullTime
	// Record deletion time
	DeletedAt sql.NullTime
}

// acc_user_two_factor
type AccUserTwoFactor struct {
	TwoFactorID         uint32
	UserID              uint32
	TwoFactorAuthType   AccUserTwoFactorTwoFactorAuthType
	TwoFactorAuthSecret string
	TwoFactorPhone      sql.NullString
	TwoFactorEmail      sql.NullString
	TwoFactorIsActive   bool
	TwoFactorCreatedAt  sql.NullTime
	TwoFactorUpdatedAt  sql.NullTime
}

// account_user_verify
type AccUserVerify struct {
	VerifyID        int32
	VerifyOtp       string
	VerifyKey       string
	VerifyKeyHash   string
	VerifyType      sql.NullInt32
	IsVerified      sql.NullInt32
	IsDeleted       sql.NullInt32
	VerifyCreatedAt sql.NullTime
	VerifyUpdatedAt sql.NullTime
}
