// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: trans_trip_query.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const addTrip = `-- name: AddTrip :execresult
INSERT INTO trips (
    trip_departure_time, trip_arrival_time, trip_base_price, trip_created_at, trip_updated_at
) VALUES (
    ?, ?, ?, ?, ?
)
`

type AddTripParams struct {
	TripDepartureTime time.Time
	TripArrivalTime   time.Time
	TripBasePrice     string
	TripCreatedAt     sql.NullTime
	TripUpdatedAt     sql.NullTime
}

func (q *Queries) AddTrip(ctx context.Context, arg AddTripParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addTrip,
		arg.TripDepartureTime,
		arg.TripArrivalTime,
		arg.TripBasePrice,
		arg.TripCreatedAt,
		arg.TripUpdatedAt,
	)
}

const deleteForceTrip = `-- name: DeleteForceTrip :exec
DELETE FROM trips WHERE trip_id = ?
`

func (q *Queries) DeleteForceTrip(ctx context.Context, tripID int64) error {
	_, err := q.db.ExecContext(ctx, deleteForceTrip, tripID)
	return err
}

const deleteTrip = `-- name: DeleteTrip :exec
UPDATE trips
SET trip_deleted_at = NOW()
WHERE trip_id = ?
`

func (q *Queries) DeleteTrip(ctx context.Context, tripID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTrip, tripID)
	return err
}

const getListTrips = `-- name: GetListTrips :many
SELECT trip_id, routes.route_start_location, routes.route_end_location, trips.trip_departure_time, trips.trip_arrival_time, trips.trip_base_price
FROM trips
JOIN routes ON trips.route_id = routes.route_id 
WHERE trips.trip_departure_time >= ? AND routes.route_start_location = ? AND routes.route_end_location = ? AND trips.trip_deleted_at IS NULL
ORDER BY trips.trip_departure_time ASC
LIMIT 10 OFFSET ?
`

type GetListTripsParams struct {
	TripDepartureTime  time.Time
	RouteStartLocation string
	RouteEndLocation   string
	Offset             int32
}

type GetListTripsRow struct {
	TripID             int64
	RouteStartLocation string
	RouteEndLocation   string
	TripDepartureTime  time.Time
	TripArrivalTime    time.Time
	TripBasePrice      string
}

func (q *Queries) GetListTrips(ctx context.Context, arg GetListTripsParams) ([]GetListTripsRow, error) {
	rows, err := q.db.QueryContext(ctx, getListTrips,
		arg.TripDepartureTime,
		arg.RouteStartLocation,
		arg.RouteEndLocation,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetListTripsRow
	for rows.Next() {
		var i GetListTripsRow
		if err := rows.Scan(
			&i.TripID,
			&i.RouteStartLocation,
			&i.RouteEndLocation,
			&i.TripDepartureTime,
			&i.TripArrivalTime,
			&i.TripBasePrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getListTripsCount = `-- name: GetListTripsCount :one
SELECT COUNT(trip_id)
FROM trips
JOIN routes ON trips.route_id = routes.route_id 
WHERE trips.trip_departure_time >= ? AND routes.route_start_location = ? AND routes.route_end_location = ? AND trips.trip_deleted_at IS NULL
`

type GetListTripsCountParams struct {
	TripDepartureTime  time.Time
	RouteStartLocation string
	RouteEndLocation   string
}

func (q *Queries) GetListTripsCount(ctx context.Context, arg GetListTripsCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getListTripsCount, arg.TripDepartureTime, arg.RouteStartLocation, arg.RouteEndLocation)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTripById = `-- name: GetTripById :one
SELECT trip_id, route_id, bus_id, trip_departure_time, trip_arrival_time, trip_base_price, trip_created_at, trip_updated_at, trip_deleted_at
FROM ` + "`" + `trips` + "`" + `
WHERE trip_id = ?
`

func (q *Queries) GetTripById(ctx context.Context, tripID int64) (Trip, error) {
	row := q.db.QueryRowContext(ctx, getTripById, tripID)
	var i Trip
	err := row.Scan(
		&i.TripID,
		&i.RouteID,
		&i.BusID,
		&i.TripDepartureTime,
		&i.TripArrivalTime,
		&i.TripBasePrice,
		&i.TripCreatedAt,
		&i.TripUpdatedAt,
		&i.TripDeletedAt,
	)
	return i, err
}

const getTripDetail = `-- name: GetTripDetail :one
SELECT trips.trip_id, 
    routes.route_id,
    routes.route_start_location, 
    routes.route_end_location, 
    trips.trip_departure_time, 
    trips.trip_arrival_time, 
    trips.trip_base_price,
    buses.bus_license_plate, 
    buses.bus_company, 
    buses.bus_capacity,
    buses.bus_id
FROM trips
JOIN routes ON trips.route_id = routes.route_id 
JOIN buses ON trips.bus_id = buses.bus_id
WHERE trips.trip_id = ? AND trips.trip_deleted_at IS NULL
`

type GetTripDetailRow struct {
	TripID             int64
	RouteID            int32
	RouteStartLocation string
	RouteEndLocation   string
	TripDepartureTime  time.Time
	TripArrivalTime    time.Time
	TripBasePrice      string
	BusLicensePlate    string
	BusCompany         string
	BusCapacity        int32
	BusID              int32
}

func (q *Queries) GetTripDetail(ctx context.Context, tripID int64) (GetTripDetailRow, error) {
	row := q.db.QueryRowContext(ctx, getTripDetail, tripID)
	var i GetTripDetailRow
	err := row.Scan(
		&i.TripID,
		&i.RouteID,
		&i.RouteStartLocation,
		&i.RouteEndLocation,
		&i.TripDepartureTime,
		&i.TripArrivalTime,
		&i.TripBasePrice,
		&i.BusLicensePlate,
		&i.BusCompany,
		&i.BusCapacity,
		&i.BusID,
	)
	return i, err
}

const updateTrip = `-- name: UpdateTrip :execrows
UPDATE trips
SET trip_updated_at = NOW(), trip_departure_time = ?, trip_arrival_time = ?, trip_base_price = ?
WHERE trip_id = ? AND trip_updated_at = ? AND trip_deleted_at IS NULL
`

type UpdateTripParams struct {
	TripDepartureTime time.Time
	TripArrivalTime   time.Time
	TripBasePrice     string
	TripID            int64
	TripUpdatedAt     sql.NullTime
}

func (q *Queries) UpdateTrip(ctx context.Context, arg UpdateTripParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTrip,
		arg.TripDepartureTime,
		arg.TripArrivalTime,
		arg.TripBasePrice,
		arg.TripID,
		arg.TripUpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
