basePath: /v1
definitions:
  response.ErrorResponseData:
    properties:
      code:
        type: integer
      detail: {}
      error:
        type: string
      success:
        type: boolean
    type: object
  response.ResponseData:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
      success:
        type: boolean
    type: object
  usercommandrequest.UserRegistratorRequest:
    properties:
      email:
        type: string
      purpose:
        description: TEST_USER, CUSTOMER, ADMIN, etc.
        type: string
    required:
    - email
    - purpose
    type: object
host: localhost:8002
info:
  contact:
    email: tipsgo@gmail.com
    name: TEAM TIPSGO
    url: github.com/anonystick/go-ecommerce-backend-go
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: github.com/anonystick/go-ecommerce-backend-go
  title: API Documentation Ecommerce Backend SHOPDEVGO
  version: 1.0.0
paths:
  /auth/register:
    post:
      consumes:
      - application/json
      description: When user is registered send otp to email
      parameters:
      - description: payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/usercommandrequest.UserRegistratorRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponseData'
      summary: User Registration
      tags:
      - account management
  /user/{id}:
    get:
      consumes:
      - application/json
      description: Returns user details data based on ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponseData'
      summary: Get user details by ID
      tags:
      - user
swagger: "2.0"
